### ISSUE TITLE
Compatibilidad-con-Mac-Os

### ISSUE THREAD

**Issue by masteread** [parzibyte/plugin-impresora-termica-v3#1]
Hola! Primeramente: GRACIAS!
 Me parece un proyecto brillante y quiero ayudarte a hacerlo compatible con MACOS si es que te parece y estás de acuerdo.

¿Haz intentando realizar esa compatibilidad? ¿Sí .. No?

¿Cómo puedo ayudarte?

**Comment by parzibyte** [comment]
Hola. Claro que sí, lo haré compatible tan pronto cuente con las herramientas necesarias para compilarlo en macOS.
