### ISSUE TITLE
Printing Error: Undefined

### ISSUE THREAD

**Issue by clvanwinkle83** [parzibyte/plugin-impresora-termica-v3#2]
Since this morning I am no longer able to print via the online app.

When I go to print it only prints  your footer watermarking.

I am using windows 10

I have:
Restarted my PC and Printer
Checked task under details and made sure the plugin is active.

**Comment by parzibyte** [comment]
Hi. Which online app do you mean? do you mean the [ESC POS ticket designer](https://parzibyte.me/apps/ticket-designer/#/)? I have updated it recently. Make sure you are using the latest version and the plugin 3.5.0
To make sure you are using both plugin and designer latest versions, in the designer, the plugin should say version 3.5.0 and when you add a image in the designer it should have a checkbox asking wether to apply dithering or not.
